apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: test-app
    image: jinshuangniu/advanced1cloud1computing:test-app-1.0
    imagePullPolicy: Always
    # readinessProbe:
    #   exec:
    #     command:
    #     - "/bin/sh"
    #     - "-c"
    #     - "curl -f localhost:8080/health"
    ports:
    - containerPort: 8080
  initContainers:
  - name: schema-migration
    image: jinshuangniu/advanced1cloud1computing:db-1677781554
    command: ["flyway", "migrate"]
    volumeMounts:
    - name: ssh-key
      mountPath: /root/.ssh
  restartPolicy: Always

  volumes:
  - name: ssh-key
    secret:
      secretName: ssh-key-secret
      items:
      - key: ssh-privatekey
        path: 
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  nodeSelector:
    bastion: "true"
---