apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: jinshuangniu/advanced1cloud1computing:db.01
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: db-init-container
    image: jinshuangniu/advanced1cloud1computing:db.01
    command: ['sh', '-c', 'echo The database is running!']